name: shop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

fonts:
  - family: Lato
    fonts:
      - assets: assets/fonts/Lato-Regular.ttf
      - assets: assets/fonts/Lato-Bold.ttf
        weigth: 700
  - family: Anton
    fonts:
      - assets: assets/fonts/Anton-Regular.ttf
